DROP TABLE IF EXISTS Test
GO

CREATE TABLE Test (ID INT PRIMARY KEY, Liczba INT)

INSERT INTO Test VALUES(1, 100)
INSERT INTO Test VALUES(2, 200)
INSERT INTO Test VALUES(3, 300)
INSERT INTO Test VALUES(4, 400)
INSERT INTO Test VALUES(5, 500)
GO