SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; 

BEGIN TRAN
UPDATE Test SET Liczba = 100 WHERE ID = 2
UPDATE Test SET Liczba = 100 WHERE ID = 3
WAITFOR DELAY '00:00:10'
SELECT * FROM Test
ROLLBACK TRANSACTION
SELECT * FROM Test